### PR TITLE
Include system library paths in Configure.pl if configured to use them

### LINKED ISSUE #1000: Configure.pl fails when including system libraries with clang
```
bastille% ./Configure.pl --has-libtommath --cc=clang 
Welcome to MoarVM!

Updating submodules .................................... OK
Configuring native build environment ................... 
    trying to compile a simple C program ............... YES
    Testing pkgconfig .................................. 0.27.1
OK

    probing whether your compiler thinks that it is gcc  Can't compile simple gcc probe, so something is badly wrong at build/probe.pm line 147.
```

The same error happens with `--has-dyncall`, `--has-libuv`, etc. I'm not sure if this happens or not on Linux, I tested on OpenBSD 6.4 with the GENERIC.MP kernel

### PR DESCRIPTION
**Pull request by Kaiepi**
Fixes #1000

### CODE REVIEW

File: Configure.pl [hunk 1]
```diff
@@ -851,6 +834,35 @@ sub wsl_bash_on_win {
...
+        }
+    }
+    else {
+        print("Error occured when running $config{pkgconfig} --cflags $library.\n");
+    }
+    my $result_libs = `$config{pkgconfig} --libs-only-L $library`;
+    if ( $? == 0 ) {
+        $result_libs =~ s/\n//g;
+        if (index($config{lincludes}, $result_libs) == -1) {
+            $config{lincludes} .= ' ' if $config{lincludes};
```
Comment (samcv) [inline Configure.pl]: This is better written as `$config{lincludes} = join(' ', $config{lincludes}, $result_libs);`

File: Configure.pl [hunk 2]
```diff
@@ -328,6 +302,14 @@ sub uniq {
     $defaults{-thirdparty}->{dcb} = undef;
     $defaults{-thirdparty}->{dl}  = undef;
     $config{nativecall_backend} = 'dyncall';
+    if (index($config{cincludes}, '-I/usr/local/include') == -1) {
+        $config{cincludes} .= ' ' if $config{cincludes};
```
Comment (samcv) [inline Configure.pl]: Same as mentioned below about using a join instead of concatenation.

File: Configure.pl [hunk 3]
```diff
@@ -328,6 +302,14 @@ sub uniq {
...
+        $config{cincludes} .= '-I/usr/local/include';
+    }
+    if (index($config{lincludes}, '-L/usr/local/lib') == -1) {
+        $config{lincludes} .= ' ' if $config{lincludes};
```
Comment (samcv) [inline Configure.pl]: Same as mentioned below about using a join instead of concatenation.

File: Configure.pl [hunk 4]
```diff
@@ -851,6 +834,35 @@ sub wsl_bash_on_win {
...
 }
 
+# set up cincludes and ldusr flags for a native library
+sub setup_native_libraries {
+    my $library = shift;
+    my $result_cflags = `$config{pkgconfig} --cflags $library`;
+    if ( $? == 0 ) {
+        $result_cflags =~ s/\n//g;
+        if (index($config{cincludes}, $result_cflags) == -1) {
+            $config{cincludes} .= ' ' if $config{cincludes};
```
Comment (samcv) [inline Configure.pl]: Same as mentioned below about using a join instead of concatenation.
