### PR TITLE
VMArray: Use dest for select 'kind' in copy_elements

### LINKED ISSUE #1432: Segfault in VMArray's copy_elems
`my @a := 1, 2, 3; my %b := nqp::hash; %b<a> := 1; nqp::splice(@a, %b, 1, 0)` causes a segfault here https://github.com/MoarVM/MoarVM/blob/master/src/6model/reprs/VMArray.c#L836 because `s_repr_data` ends up NULL here https://github.com/MoarVM/MoarVM/blob/master/src/6model/reprs/VMArray.c#L813-L814

Problematic MoarVM code found by the GCC static analyzer, example crafted by @niner.

### PR DESCRIPTION
**Pull request by salortiz**
dest argument is always VMArray so its REPR_data can't be NULL.
This fixes #1432

### CODE REVIEW

File: src/6model/reprs/VMArray.c [hunk 1]
```diff
@@ -812,8 +812,7 @@ static void copy_elements(MVMThreadContext *tc, MVMObject *src, MVMObject *dest,
     MVMArrayBody     *d_body      = (MVMArrayBody *)OBJECT_BODY(dest);
     MVMArrayREPRData *s_repr_data = REPR(src)->ID == MVM_REPR_ID_VMArray
                                     ? (MVMArrayREPRData *)STABLE(src)->REPR_data  : NULL;
-    MVMArrayREPRData *d_repr_data = REPR(src)->ID == MVM_REPR_ID_VMArray
-                                    ? (MVMArrayREPRData *)STABLE(dest)->REPR_data : NULL;
+    MVMArrayREPRData *d_repr_data = (MVMArrayREPRData *)STABLE(dest)->REPR_data;
```
Comment (MasterDuke17) [inline src/6model/reprs/VMArray.c:815]: If `d_repr_data` can't ever be NULL, I'd say it should be removed from the if condition on line 8211/822.

**Review by niner — APPROVED** [review]

**Review by MasterDuke17 — APPROVED** [review]
